// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockURLShortnerHandlerInterface is a mock of URLShortnerHandlerInterface interface.
type MockURLShortnerHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockURLShortnerHandlerInterfaceMockRecorder
}

// MockURLShortnerHandlerInterfaceMockRecorder is the mock recorder for MockURLShortnerHandlerInterface.
type MockURLShortnerHandlerInterfaceMockRecorder struct {
	mock *MockURLShortnerHandlerInterface
}

// NewMockURLShortnerHandlerInterface creates a new mock instance.
func NewMockURLShortnerHandlerInterface(ctrl *gomock.Controller) *MockURLShortnerHandlerInterface {
	mock := &MockURLShortnerHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockURLShortnerHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLShortnerHandlerInterface) EXPECT() *MockURLShortnerHandlerInterfaceMockRecorder {
	return m.recorder
}

// CreateShortUrl mocks base method.
func (m *MockURLShortnerHandlerInterface) CreateShortUrl(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateShortUrl", c)
}

// CreateShortUrl indicates an expected call of CreateShortUrl.
func (mr *MockURLShortnerHandlerInterfaceMockRecorder) CreateShortUrl(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortUrl", reflect.TypeOf((*MockURLShortnerHandlerInterface)(nil).CreateShortUrl), c)
}

// FetchOriginalURL mocks base method.
func (m *MockURLShortnerHandlerInterface) FetchOriginalURL(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FetchOriginalURL", c)
}

// FetchOriginalURL indicates an expected call of FetchOriginalURL.
func (mr *MockURLShortnerHandlerInterfaceMockRecorder) FetchOriginalURL(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOriginalURL", reflect.TypeOf((*MockURLShortnerHandlerInterface)(nil).FetchOriginalURL), c)
}
